services:
  # back
  back:
    container_name: tecflix_back
    build: ./back
    env_file:
      - ./db.env
      - ./back/.env
    ports:
      - 8081:8081
    depends_on:
      - postgres
    networks:
      - app
    restart: on-failure:2

  # postgres
  postgres:
    image: postgres:17-alpine
    container_name: tecflix_postgres
    ports:
      - 2345:5432
    env_file:
      - ./db.env
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data
    restart: on-failure:2
    networks:
      - app

# volumes:
#   postgres_data:

networks:
  app: