services:
  # nginx
  # nginx:

  # back
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./db.env
      - ./backend/.env
    ports:
      - 8081:8081
    depends_on:
      - postgres
    networks:
      - app
    restart: on-failure:2

  # postgres
  postgres:
    image: postgres:17-alpine
    container_name: postgres
    ports:
      - 2345:5432
    env_file:
      - ./db.env
    restart: on-failure:2
    networks:
      - app
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

networks:
  app:
