CREATE TABLE IF NOT EXISTS payments(
    id SERIAL PRIMARY KEY,
    course_id UUID REFERENCES courses(id) NOT NULL,
    user_id UUID REFERENCES users(id) NOT NULL,
    price DECIMAL(5,2) NOT NULL,
    moment TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);