server:
  port: ${SERVER_PORT:8081}

security:
  api:
    key: ${API_KEY:password}
  jwt:
    token:
      secret: ${TOKEN_SECRET:mySecret}
      duration: ${TOKEN_DURATION:43200000} # 12 hours
      refresh:
        duration: ${REFRESH_TOKEN_DURATION:604800000} # 168 hours

spring:
  application:
    name: tecflix-app
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    jpa:
      open-in-view: false
      hibernate:
        ddl-auto: none
      show-sql: false
  flyway:
    locations:
      filesystem: src/test/resources/db/migration