server:
  port: ${SERVER_PORT:8081}

app:
  frontend:
    url: ${FRONTEND_URL}

email:
  code:
    validation:
      time: ${CODE_VALIDATION_TIME:10m}

security:
  api:
    key: ${API_KEY:password}
  jwt:
    token:
      issuer: ${TOKEN_ISSUER:tecflix}
      secret: ${TOKEN_SECRET:mySecret}
      duration: ${TOKEN_DURATION:15m}
      refresh:
        duration: ${REFRESH_TOKEN_DURATION:168h}

spring:
  application:
    name: tecflix-app
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    jpa:
      open-in-view: false
      hibernate:
        ddl-auto: none
      show-sql: false
  flyway:
    locations:
      filesystem: src/test/resources/db/migration
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USER}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

spring-doc:
  pathsToMatch:
    - /api/**

  swagger-ui:
    use-root-path: true
