CREATE TABLE IF NOT EXISTS classes(
    id UUID PRIMARY KEY,
    title VARCHAR(20) NOT NULL,
    video_path VARCHAR(255) NOT NULL,
    module_id SERIAL REFERENCES modules(id) NOT NULL,
    active BOOLEAN DEFAULT FALSE NOT NULL, 
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);